Description:
  This template deploys a Notebook Instance, which is part of the environments used on this project.

Parameters:

  ProjectTag:
    Description: Project name to be associated to each resource as a tag.
    Type: String
    Default: "ArturoBayo-project"
    AllowedValues:
      - "ArturoBayo-project"

  NotebookInstanceName:
    Description: Name for the Notebook Instance that is going to be created
    Type: String

  NotebookInstanceType:
    Description: Please enter the instance type for the Notebook Instance
    Type: String
    Default: "ml.t2.large"
    AllowedValues:
      - "ml.t2.medium"
      - "ml.t2.large"
      - "ml.t2.xlarge"
      - "ml.t2.2xlarge"
      - "ml.m4.xlarge"
      - "ml.m4.2xlarge"
      - "ml.m4.4xlarge"
      - "ml.m4.10xlarge"
      - "ml.m4.16xlarge"
      - "ml.p2.xlarge"
      - "ml.p2.8xlarge"
      - "ml.p2.16xlarge"
      - "ml.p3.2xlarge"
      - "ml.p3.8xlarge"
      - "ml.p3.16xlarge"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "General configuration"
        Parameters:
          - ProjectTag
          - NotebookInstanceName
          - NotebookInstanceType
    ParameterLabels:
      ProjectTag:
        default: "Project name"
      NotebookInstanceName:
        default: "Notebook Instance Name"
      NotebookInstanceType:
        default: "Instance type for the notebook instance"


Resources:

  SageMakerExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
      Path: "/service-role/"

  DevelopmentEnvironment:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      DirectInternetAccess: "Enabled"
      NotebookInstanceName: !Ref NotebookInstanceName
      InstanceType: !Ref NotebookInstanceType
      #LifecycleConfigName: String
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      Tags:
        -
          Key: "Project"
          Value: !Ref ProjectTag
Outputs:
  DevelopmentEnvironment:
    Description: A reference to the created Notebook Instance
    Value: !Ref DevelopmentEnvironment
